<!DOCTYPE html>
<html>
    <head>
        <style type="text/css">
          html { height: 100% }
          body { height: 100%; margin: 0px; padding: 0px }
          #map_canvas { height: 100% }
        </style>

        <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
        <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=true">
        </script>
        <script type="text/javascript" src="/scripts/js/jquery-1.5.min.js"></script>
        <script type="text/javascript" src="/scripts/js/jquery.jcarousel.min.js"></script>
        <link rel="stylesheet" type="text/css" href="/scripts/skins/tango/skin.css" />

        <script type="text/javascript">
    jQuery(document).ready(function() {
    jQuery('#sightingsroller').jcarousel({
        vertical:true,
        visible:5,
        scroll:1,
        auto:5,
        wrap:"circular",
        buttonNextHTML:null,
        buttonPrevHTML:null

    });
});
</script>


    </head>

    
    
    <script type="text/javascript" >
        var map;

        this.getElementById('latitude').setValu;

function init(){


var myLatlng = new google.maps.LatLng(51.420908, -0.221169);
var myOptions = {
  zoom: 8,
  center: myLatlng,
  mapTypeId: google.maps.MapTypeId.ROADMAP
};

map = new google.maps.Map(document.getElementById("map_canvas"),
    myOptions);


 google.maps.event.addListener(map, 'click', function(event) {
    placeMarker(event.latLng);
    document.getElementById('latitude').value = event.latLng.lat();
    document.getElementById('longitude').value = event.latLng.lng();
    //alert(document.getElementById('longitude').value);


  });
}

function placeMarker(location) {
  var marker = new google.maps.Marker({
      position: location,
      map: map
  });


}

</script>
    <body onload="init();">

        <div>
        <h1>Twitcher</h1>
        </div>
        <div>
            <?php echo $this->layout()->content; ?>
        </div>


</body>


</html>